"""Tests for the requirements parser across CSV, Markdown, Word, and Excel formats."""

from pathlib import Path

import pytest

from pm_agent_system.tools.requirements_parser import (
    CustomerRequirement,
    _normalize_priority,
    parse_requirements_file,
)

FIXTURES = Path(__file__).parent / "fixtures" / "requirements"


# ---------- CSV ----------


class TestCSVParser:
    def test_basic_csv(self):
        reqs = parse_requirements_file(str(FIXTURES / "basic.csv"))
        assert len(reqs) == 4
        assert reqs[0].title == "User login"
        assert reqs[0].priority == "P0"
        assert reqs[0].category == "Authentication"
        assert reqs[0].notes == "MVP feature"
        assert all(r.source == "customer_input" for r in reqs)

    def test_alternate_headers(self):
        reqs = parse_requirements_file(str(FIXTURES / "alternate_headers.csv"))
        assert len(reqs) == 3
        assert reqs[0].title == "Login flow"
        assert reqs[0].id == "REQ-001"
        assert reqs[0].priority == "P0"  # "Must have" → P0
        assert reqs[1].priority == "P1"  # "High" → P1
        assert reqs[2].priority == "P2"  # "Could have" → P2
        assert reqs[0].category == "Auth"

    def test_minimal_csv_no_priority(self):
        reqs = parse_requirements_file(str(FIXTURES / "minimal.csv"))
        assert len(reqs) == 2
        assert reqs[0].title == "Feature A"
        assert reqs[0].priority == "unspecified"

    def test_autogenerated_ids(self):
        reqs = parse_requirements_file(str(FIXTURES / "minimal.csv"))
        assert reqs[0].id == "CR-001"
        assert reqs[1].id == "CR-002"

    def test_no_recognizable_columns_raises(self):
        with pytest.raises(ValueError, match="Could not parse"):
            parse_requirements_file(str(FIXTURES / "no_recognizable_columns.csv"))

    def test_empty_csv_raises(self):
        with pytest.raises(ValueError, match="Could not parse"):
            parse_requirements_file(str(FIXTURES / "empty.csv"))

    def test_file_not_found(self):
        with pytest.raises(FileNotFoundError):
            parse_requirements_file("/tmp/nonexistent_requirements.csv")

    def test_unsupported_extension(self, tmp_path):
        bad = tmp_path / "reqs.json"
        bad.write_text("{}")
        with pytest.raises(ValueError, match="Could not parse"):
            parse_requirements_file(str(bad))


# ---------- Markdown ----------


class TestMarkdownParser:
    def test_table_format(self):
        reqs = parse_requirements_file(str(FIXTURES / "basic_table.md"))
        assert len(reqs) == 3
        assert reqs[0].title == "User login"
        assert reqs[0].priority == "P0"
        assert reqs[2].priority == "P2"

    def test_header_based_format(self):
        reqs = parse_requirements_file(str(FIXTURES / "header_based.md"))
        assert len(reqs) >= 3
        # Check priority extraction from body text
        titles = [r.title for r in reqs]
        assert "Login flow" in titles
        login = next(r for r in reqs if r.title == "Login flow")
        assert login.priority == "P0"

    def test_list_based_format(self):
        reqs = parse_requirements_file(str(FIXTURES / "list_based.md"))
        assert len(reqs) >= 3
        priorities = [r.priority for r in reqs]
        assert "P0" in priorities
        assert "P1" in priorities


# ---------- Priority normalization ----------


class TestPriorityNormalization:
    def test_standard_priorities(self):
        assert _normalize_priority("P0") == "P0"
        assert _normalize_priority("p1") == "P1"
        assert _normalize_priority("P2") == "P2"
        assert _normalize_priority("p3") == "P3"
        assert _normalize_priority("P4") == "P4"

    def test_natural_language_priorities(self):
        assert _normalize_priority("must have") == "P0"
        assert _normalize_priority("Must-Have") == "P0"
        assert _normalize_priority("critical") == "P0"
        assert _normalize_priority("should have") == "P1"
        assert _normalize_priority("High") == "P1"
        assert _normalize_priority("could have") == "P2"
        assert _normalize_priority("medium") == "P2"
        assert _normalize_priority("low") == "P3"
        assert _normalize_priority("backlog") == "P4"
        assert _normalize_priority("future consideration") == "P3"

    def test_empty_and_whitespace(self):
        assert _normalize_priority("") == "unspecified"
        assert _normalize_priority("  ") == "unspecified"

    def test_unknown_priority_passthrough(self):
        assert _normalize_priority("SomethingCustom") == "SomethingCustom"

    def test_priority_variants_csv(self):
        reqs = parse_requirements_file(str(FIXTURES / "priority_variants.csv"))
        assert len(reqs) == 9
        assert reqs[0].priority == "P0"  # P0
        assert reqs[1].priority == "P0"  # must have
        assert reqs[2].priority == "P1"  # High
        assert reqs[3].priority == "P2"  # could-have
        assert reqs[4].priority == "P3"  # Low
        assert reqs[5].priority == "P4"  # Backlog
        assert reqs[6].priority == "P3"  # future consideration
        assert reqs[7].priority == "unspecified"  # empty
        assert reqs[8].priority == "SomethingCustom"  # passthrough


# ---------- Word (DOCX) ----------


class TestDocxParser:
    def test_docx_with_table(self, tmp_path):
        import docx

        doc = docx.Document()
        table = doc.add_table(rows=4, cols=3)
        headers = ["Title", "Description", "Priority"]
        for i, h in enumerate(headers):
            table.rows[0].cells[i].text = h
        data = [
            ("Login", "User login feature", "P0"),
            ("Search", "Full-text search", "P1"),
            ("Export", "CSV export", "P2"),
        ]
        for row_idx, (t, d, p) in enumerate(data, start=1):
            table.rows[row_idx].cells[0].text = t
            table.rows[row_idx].cells[1].text = d
            table.rows[row_idx].cells[2].text = p

        path = tmp_path / "reqs.docx"
        doc.save(str(path))

        reqs = parse_requirements_file(str(path))
        assert len(reqs) == 3
        assert reqs[0].title == "Login"
        assert reqs[0].priority == "P0"

    def test_docx_with_headings(self, tmp_path):
        import docx

        doc = docx.Document()
        doc.add_heading("Requirements", level=1)
        doc.add_heading("Authentication", level=2)
        doc.add_heading("Login", level=3)
        doc.add_paragraph("Users log in with email. Priority: P0")
        doc.add_heading("Password reset", level=3)
        doc.add_paragraph("Reset via email link. P1")

        path = tmp_path / "reqs_headings.docx"
        doc.save(str(path))

        reqs = parse_requirements_file(str(path))
        assert len(reqs) >= 2


# ---------- Excel ----------


class TestExcelParser:
    def test_basic_excel(self, tmp_path):
        import openpyxl

        wb = openpyxl.Workbook()
        ws = wb.active
        ws.append(["Title", "Description", "Priority", "Category"])
        ws.append(["Login", "User login feature", "P0", "Auth"])
        ws.append(["Search", "Full-text search", "P1", "Core"])
        ws.append(["Export", "CSV export", "nice to have", "Data"])

        path = tmp_path / "reqs.xlsx"
        wb.save(str(path))

        reqs = parse_requirements_file(str(path))
        assert len(reqs) == 3
        assert reqs[0].title == "Login"
        assert reqs[0].priority == "P0"
        assert reqs[2].priority == "P2"  # "nice to have" → P2
        assert reqs[0].category == "Auth"

    def test_excel_alternate_headers(self, tmp_path):
        import openpyxl

        wb = openpyxl.Workbook()
        ws = wb.active
        ws.append(["Requirement Name", "Detail", "Importance"])
        ws.append(["SSO Login", "Single sign-on", "Critical"])
        ws.append(["Audit Trail", "Track actions", "Medium"])

        path = tmp_path / "reqs_alt.xlsx"
        wb.save(str(path))

        reqs = parse_requirements_file(str(path))
        assert len(reqs) == 2
        assert reqs[0].title == "SSO Login"
        assert reqs[0].priority == "P0"  # Critical → P0
        assert reqs[1].priority == "P2"  # Medium → P2
